name: Gated Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.16.3'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependancies
        run: npm install
      - name: Build
        run: npm run build
